### ISSUE TITLE
Error in connect command

### ISSUE THREAD

**Issue by airamrguez** [zeplin/cli-connect-react-plugin#18] opened 2020-05-07 10:59 UTC
I'm getting this error when executing `zeplin connect`. It was working until I upgraded node version to v14.2.0. Don't know if it's related though.

```
/.config/yarn/global/node_modules/@zeplin/cli-connect-react-plugin/dist/template/base.pug:18
        16|
        17| mixin propType(name, propType)
      > 18|     if propType.name === "union"
        19|         |   #{name}={union[
        20|         +propertyValues(propType.value)
        21|         | }]

    Cannot read property 'name' of undefined
```

**Comment by yuqu** [comment] 2020-05-11 12:13
Hey Airam, 

I could not reproduce any issues with the plugin using node v14.2.0.

The error will be gone after https://github.com/zeplin/cli-connect-react-plugin/pull/17 is merged. However, the actualy root cause is that react-docgen could not read `type`, `tsType` or `flowType` of any of your components, so one of your component fields may not be shown in the resulting code snippet.

I can help you if you could share a sample code, feel free to open the issue again if the PR does not work for you.

**Closed by yuqu** 2020-05-11 12:13 UTC
Labels: duplicate
